// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form: dynamic(() => import("./ContactForm")),
  get_on_list: dynamic(() => import("./GetOnList")),
  hero: dynamic(() => import("./Hero")),
  introduction: dynamic(() => import("./Introduction")),
  results: dynamic(() => import("./Results")),
  steps: dynamic(() => import("./Steps")),
};
